In [1]:
import panda_dataset as pds
import matplotlib.pyplot as plt
import numpy as np
from torch.utils.data import DataLoader

from PIL import Image
from IPython import display

In [2]:
def as_gif(images, path="sample.gif"):
    images[0].save(path, save_all=True, append_images=images, duration=int(1000/30), loop=0)
    gif_bytes = open(path,"rb").read()
    return gif_bytes

In [12]:
# Prints camera intrinsics and extrinsics and outputs a gif for each episode
panda_dataset = pds.PandaDataset(root_dir="./panda_dataset", transform=pds.ToTensor())
dataloader = DataLoader(panda_dataset, batch_size=1, num_workers=0)
for i_batch, sample_batched in enumerate(dataloader):
    images = []
    timestamps = sample_batched["timestamps"]
    cam_in = sample_batched["calibration_info"]["intrinsic"][0]
    cam_ex = sample_batched["calibration_info"]["extrinsic"][0]
    print(f"Camera Intrinsics:\n{cam_in}")
    print(f"Camera Extrinsics:\n{cam_ex}")
    for i, timestamp in enumerate(sample_batched["steps"]):
        step = sample_batched["steps"][timestamp]
        image = step["img_data"].squeeze().permute(1,2,0).numpy()
        images.append(Image.fromarray(image))
    ep_num = str(i_batch+1).zfill(4)
    as_gif(images, path=f"./assets/gifs/panda_{ep_num}.gif")


Camera Intrinsics:
tensor([[151.1343,   0.0000, 160.0976],
        [  0.0000, 151.1347, 120.6547],
        [  0.0000,   0.0000,   1.0000]], dtype=torch.float64)
Camera Extrinsics:
tensor([[ 0.8729, -2.1360,  1.4145,  0.5159,  0.4621,  0.3596]],
       dtype=torch.float64)
Camera Intrinsics:
tensor([[151.1343,   0.0000, 160.0976],
        [  0.0000, 151.1347, 120.6547],
        [  0.0000,   0.0000,   1.0000]], dtype=torch.float64)
Camera Extrinsics:
tensor([[ 0.8729, -2.1360,  1.4145,  0.5159,  0.4621,  0.3596]],
       dtype=torch.float64)
Camera Intrinsics:
tensor([[151.1343,   0.0000, 160.0976],
        [  0.0000, 151.1347, 120.6547],
        [  0.0000,   0.0000,   1.0000]], dtype=torch.float64)
Camera Extrinsics:
tensor([[ 0.8729, -2.1360,  1.4145,  0.5159,  0.4621,  0.3596]],
       dtype=torch.float64)
Camera Intrinsics:
tensor([[151.1343,   0.0000, 160.0976],
        [  0.0000, 151.1347, 120.6547],
        [  0.0000,   0.0000,   1.0000]], dtype=torch.float64)
Camera Extrinsics:
t

In [ ]:

panda_dataset = pds.PandaDataset(root_dir="./panda_dataset", transform=pds.ToTensor())
dataloader = DataLoader(panda_dataset, batch_size=1, num_workers=0)
for i_batch, sample_batched in enumerate(dataloader):
    images = []
    timestamps = sample_batched["timestamps"]
    for i, timestamp in enumerate(sample_batched["steps"]):
        step = sample_batched["steps"][timestamp]
        image = step["img_data"].squeeze().numpy()