In [3]:
import panda_dataset as pds
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader

In [7]:
panda_dataset = pds.PandaDataset(root_dir="./panda_dataset", transform=pds.ToTensor())
dataloader = DataLoader(panda_dataset, batch_size=1, num_workers=0)
images = []
for i_batch, sample_batched in enumerate(dataloader):
    timestamps = sample_batched["timestamps"]
    cam_in = sample_batched["calibration_info"]["intrinsic"][0]
    cam_ex = sample_batched["calibration_info"]["extrinsic"][0]
    print(f"Camera Intrinsics:\n{cam_in}")
    print(f"Camera Extrinsics:\n{cam_ex}")
    plt.imsave("sample_img.png", sample_batched["steps"][timestamps[200][0]]["img_data"][0].numpy().transpose((1,2,0)))

Camera Intrinsics:
tensor([[151.1343,   0.0000, 160.0976],
        [  0.0000, 151.1347, 120.6547],
        [  0.0000,   0.0000,   1.0000]], dtype=torch.float64)
Camera Extrinsics:
tensor([[ 0.8729, -2.1360,  1.4145,  0.5159,  0.4621,  0.3596]],
       dtype=torch.float64)
Camera Intrinsics:
tensor([[151.1343,   0.0000, 160.0976],
        [  0.0000, 151.1347, 120.6547],
        [  0.0000,   0.0000,   1.0000]], dtype=torch.float64)
Camera Extrinsics:
tensor([[ 0.8729, -2.1360,  1.4145,  0.5159,  0.4621,  0.3596]],
       dtype=torch.float64)
Camera Intrinsics:
tensor([[151.1343,   0.0000, 160.0976],
        [  0.0000, 151.1347, 120.6547],
        [  0.0000,   0.0000,   1.0000]], dtype=torch.float64)
Camera Extrinsics:
tensor([[ 0.8729, -2.1360,  1.4145,  0.5159,  0.4621,  0.3596]],
       dtype=torch.float64)
Camera Intrinsics:
tensor([[151.1343,   0.0000, 160.0976],
        [  0.0000, 151.1347, 120.6547],
        [  0.0000,   0.0000,   1.0000]], dtype=torch.float64)
Camera Extrinsics:
t